### ISSUE TITLE
Workers getting killed on FEATURE/distributed branch

### ISSUE THREAD

**Issue by gregjohnso** [AllenCellModeling/fov_processing_pipeline#44]
```
fpp_process --distributed 1 --port 43165 --trim_data 0 --debug 0
[INFO:  81 2019-11-27 09:53:25,107] Saving in /allen/aics/modeling/gregj/projects/fov_processing_pipeline/results
[2019-11-27 17:53:26,485] INFO - prefect.FlowRunner | Beginning Flow run for 'FOV_processing_pipeline'
[INFO: 226 2019-11-27 09:53:26,485] Beginning Flow run for 'FOV_processing_pipeline'
[2019-11-27 17:53:26,487] INFO - prefect.FlowRunner | Starting flow run.
[INFO: 344 2019-11-27 09:53:26,487] Starting flow run.
[2019-11-27 18:21:23,623] ERROR - prefect.FlowRunner | Unexpected error: KilledWorker('im2diagnostics_fn-00afeb2a-af8e-49fe-a0b1-93dcf19829a4', <Worker 'tcp://172.20.5.86:41397', memory: 0, processing: 2>)
Traceback (most recent call last):
  File "/home/gregj/anaconda3/envs/fov_processing_pipeline/lib/python3.7/site-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/home/gregj/anaconda3/envs/fov_processing_pipeline/lib/python3.7/site-packages/prefect/engine/flow_runner.py", line 462, in get_flow_run_state
    for t in final_tasks
  File "/home/gregj/anaconda3/envs/fov_processing_pipeline/lib/python3.7/site-packages/prefect/engine/executors/dask.py", line 185, in wait
    return self.client.gather(futures)
  File "/home/gregj/anaconda3/envs/fov_processing_pipeline/lib/python3.7/site-packages/distributed/client.py", line 1872, in gather
    asynchronous=asynchronous,
  File "/home/gregj/anaconda3/envs/fov_processing_pipeline/lib/python3.7/site-packages/distributed/client.py", line 767, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "/home/gregj/anaconda3/envs/fov_processing_pipeline/lib/python3.7/site-packages/distributed/utils.py", line 334, in sync
    raise exc.with_traceback(tb)
  File "/home/gregj/anaconda3/envs/fov_processing_pipeline/lib/python3.7/site-packages/distributed/utils.py", line 318, in f
    result[0] = yield future
  File "/home/gregj/anaconda3/envs/fov_processing_pipeline/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/home/gregj/anaconda3/envs/fov_processing_pipeline/lib/python3.7/site-packages/distributed/client.py", line 1728, in _gather
    raise exception.with_traceback(traceback)
distributed.scheduler.KilledWorker: ('im2diagnostics_fn-00afeb2a-af8e-49fe-a0b1-93dcf19829a4', <Worker 'tcp://172.20.5.86:41397', memory: 0, processing: 2>)
[ERROR:  66 2019-11-27 10:21:23,623] Unexpected error: KilledWorker('im2diagnostics_fn-00afeb2a-af8e-49fe-a0b1-93dcf19829a4', <Worker 'tcp://172.20.5.86:41397', memory: 0, processing: 2>)
Traceback (most recent call last):
  File "/home/gregj/anaconda3/envs/fov_processing_pipeline/lib/python3.7/site-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/home/gregj/anaconda3/envs/fov_processing_pipeline/lib/python3.7/site-packages/prefect/engine/flow_runner.py", line 462, in get_flow_run_state
    for t in final_tasks
  File "/home/gregj/anaconda3/envs/fov_processing_pipeline/lib/python3.7/site-packages/prefect/engine/executors/dask.py", line 185, in wait
    return self.client.gather(futures)
  File "/home/gregj/anaconda3/envs/fov_processing_pipeline/lib/python3.7/site-packages/distributed/client.py", line 1872, in gather
    asynchronous=asynchronous,
  File "/home/gregj/anaconda3/envs/fov_processing_pipeline/lib/python3.7/site-packages/distributed/client.py", line 767, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "/home/gregj/anaconda3/envs/fov_processing_pipeline/lib/python3.7/site-packages/distributed/utils.py", line 334, in sync
    raise exc.with_traceback(tb)
  File "/home/gregj/anaconda3/envs/fov_processing_pipeline/lib/python3.7/site-packages/distributed/utils.py", line 318, in f
    result[0] = yield future
  File "/home/gregj/anaconda3/envs/fov_processing_pipeline/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/home/gregj/anaconda3/envs/fov_processing_pipeline/lib/python3.7/site-packages/distributed/client.py", line 1728, in _gather
    raise exception.with_traceback(traceback)
distributed.scheduler.KilledWorker: ('im2diagnostics_fn-00afeb2a-af8e-49fe-a0b1-93dcf19829a4', <Worker 'tcp://172.20.5.86:41397', memory: 0, processing: 2>)
[2019-11-27 18:21:23,665] ERROR - prefect.Flow: FOV_processing_pipeline | Unexpected error occured in FlowRunner: KilledWorker('im2diagnostics_fn-00afeb2a-af8e-49fe-a0b1-93dcf19829a4', <Worker 'tcp://172.20.5.86:41397', memory: 0, processing: 2>)
[ERROR:1027 2019-11-27 10:21:23,665] Unexpected error occured in FlowRunner: KilledWorker('im2diagnostics_fn-00afeb2a-af8e-49fe-a0b1-93dcf19829a4', <Worker 'tcp://172.20.5.86:41397', memory: 0, processing: 2>)
Traceback (most recent call last):
  File "/home/gregj/anaconda3/envs/fov_processing_pipeline/bin/fpp_process", line 11, in <module>
    load_entry_point('fov-processing-pipeline', 'console_scripts', 'fpp_process')()
  File "/allen/aics/modeling/gregj/projects/fov_processing_pipeline/fov_processing_pipeline/bin/process.py", line 93, in main
    debug=p.debug,
  File "/allen/aics/modeling/gregj/projects/fov_processing_pipeline/fov_processing_pipeline/bin/process.py", line 307, in process_distributed
    df_stats = state.result[flow.get_tasks(name="load_stats_fn")[0]].result
TypeError: 'KilledWorker' object is not subscriptable
```

**Comment by jcass11** [comment]
Addressed in PR #46
